name: Manual Branch Scan Workflow

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Enter the branch to scan (e.g., testbranch)'
        required: true
        default: 'main'
      scan-type:
        description: 'Select scan type'
        required: true
        type: choice
        options:
          - mend
          - snyk
          - both
        default: 'mend'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}

      - name: Run Mend Scan
        if: ${{ github.event.inputs.scan-type == 'mend' || github.event.inputs.scan-type == 'both' }}
        run: |
          echo "Running Mend scan on branch ${{ github.event.inputs.target-branch }}"
          # Insert actual Mend scan command here
          # Example: mend-cli scan --branch ${{ github.event.inputs.target-branch }}

      - name: Run Snyk Scan
        if: ${{ github.event.inputs.scan-type == 'snyk' || github.event.inputs.scan-type == 'both' }}
        run: |
          echo "Running Snyk scan on branch ${{ github.event.inputs.target-branch }}"
          # Insert actual Snyk scan command here
          # Example: snyk test --all-projects
