name: Manual Mend Trigger with Branch Selection

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Select the branch to run the scan on'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - testbranch
      test-type:
        description: 'Select test type'
        required: true
        type: choice
        options:
          - unit
          - integration
          - both
        default: 'both'

jobs:
  run-tests:
    name: Run Tests or Mend on Selected Branch
    runs-on: ubuntu-latest

    steps:
      - name: Print selected inputs
        run: |
          echo "Selected branch: ${{ github.event.inputs.target-branch }}"
          echo "Selected test type: ${{ github.event.inputs.test-type }}"

      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}

      - name: Print current checked out branch
        run: git branch --show-current

      - name: Run test type logic (mocked for now)
        run: |
          if [ "${{ github.event.inputs.test-type }}" == "unit" ]; then
            echo "Running unit tests..."
          elif [ "${{ github.event.inputs.test-type }}" == "integration" ]; then
            echo "Running integration tests..."
          else
            echo "Running both unit and integration tests..."
          fi
